name: Git Conventions

on:
    pull_request:
        branches:
            - main

jobs:
    ensure-linear-history:
        name: Ensure Linear Git History
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Run Check
              uses: ./src/ensure_linear_history
              with:
                  target-branch: main
